@baseUrl = http://localhost:3000/users
@userToken = token
@userId = userId-to-find
### Find user by ID
GET {{baseUrl}}/{{userId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}


### Find all users with pagination
GET {{baseUrl}}?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{userToken}}
