@baseUrl = http://localhost:3000/users
@userId = ce0f04da-2fbb-47e7-9dc2-b8f1efe81d0b
### Update user by ID
PATCH {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "username": "Soy alumno"
}

### Update user rol by ID
PATCH {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "isAdmin": true
}