@baseUrl = http://localhost:3000/users
@userToken = token
@userId = userId-to-update
### Update user by ID
PATCH {{baseUrl}}/{{userId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "username": "Alumno uno"
}

### Update user rol by ID
PATCH {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "isAdmin": true
}