@baseUrl = http://localhost:3000/reviews
@userToken = token

### Create Review Request
POST {{baseUrl}}    
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "userId": "1d88137f-4e1e-45dd-85b6-82d3cb2bf93e"
}


