@baseUrl = http://localhost:3000/reviews
@adminToken = token
@reviewId = reviewId
@userId = userId

### delete review (admin only)
DELETE {{baseUrl}}/{{reviewId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### delete review by user id (admin only)
DELETE {{baseUrl}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

