@baseUrl = http://localhost:3000/reviews
@userToken = token
@reviewId = reviewId
@userId = userId
### Find Review by User
GET {{baseUrl}}/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

### Find Review by Id
GET {{baseUrl}}/{{reviewId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}
