@baseUrl = http://localhost:3000/reviews
@userToken = token
@reviewId = reviewId
### Create Review Request
POST {{baseUrl}}/{{reviewId}}/reset    
Content-Type: application/json
Authorization: Bearer {{userToken}}
