@baseUrl = http://localhost:3000/questions
@adminToken = token
### Create question (admin only)
POST {{baseUrl}}    
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "text": "¿Qué se define en la reunión de Planificación del Sprint?",
    "answers": [
      { "text": "El objetivo y trabajo del Sprint", "isCorrect": true },
      { "text": "Las vacaciones del equipo", "isCorrect": false },
      { "text": "El presupuesto del proyecto", "isCorrect": false },
      { "text": "La estrategia de la empresa", "isCorrect": false }
    ],
    "category": "4",
    "questionType": "single"
  }

### Create another question (admin only)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "text": "¿Qué son los sistemas Andon?",
    "answers": [
      { "text": "Sistemas de control visual con luces", "isCorrect": true },
      { "text": "Sistemas de estimación ágil", "isCorrect": true },
      { "text": "Sistemas de gestión de proyectos", "isCorrect": false },
      { "text": "Sistemas de pruebas automáticas", "isCorrect": false }
    ],
    "category": "6",
    "questionType": "multiple"
}

### Create another question (admin only)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "text": "¿Qué diferencia la gestión predictiva de la ágil?",
    "answers": [
      { "text": "Enfoque en plan vs enfoque en adaptación", "isCorrect": true },
      { "text": "Uso de herramientas diferentes", "isCorrect": false },
      { "text": "Duración de los proyectos", "isCorrect": false },
      { "text": "Número de personas en el equipo", "isCorrect": false }
    ],
    "category": "1",
    "questionType": "single"
  }

### Create question with two answers (admin only)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "text": "¿Cuáles son los pilares de Scrum?",
    "answers": [
      { "text": "Transparencia, inspección, adaptación", "isCorrect": true },
      { "text": "Planificación, ejecución, cierre", "isCorrect": false }
    ],
    "category": "4",
    "questionType": "simple"
  }