@baseUrl = http://localhost:3000/questions
@adminToken = token
@questionId = questionId
### delete question (admin only)
DELETE {{baseUrl}}/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

