@baseUrl = http://localhost:3000/questions
@token = token
@questionId = questionId
### find question by id
GET {{baseUrl}}/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### find all questions (paginated)
GET {{baseUrl}}?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{token}}
