@baseUrl = http://localhost:3000/exams
@userToken = token

### Create Exam Request
POST {{baseUrl}}    
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "userId": "d4a63328-ba91-47ea-9583-49862bc260b6"
}
