@baseUrl = http://localhost:3000/exams
@userToken = token
@userId = userId

### Get Exam History Request
GET  {{baseUrl}}/history/{{userId}}?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{userToken}}