@baseUrl = http://localhost:3000/exams
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidmFsdWUiOiJkMDM0OWQyNC00ZjFmLTQzZTAtODgwNi01MzQyZDY2MzE5MmMifSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlcyI6ImFkbWluIiwiaWF0IjoxNzYzNjYzMDYzLCJleHAiOjE3NjM2NjY2NjN9.lI_mKID1Zhugf03o7yijPw0QiIZ07lObdqLcaQS7Qx8
@userId = 708a95c8-9f2b-4e83-9adf-7dd17fb2e21c
### Get Exam History Request
GET  {{baseUrl}}/history/{{userId}}?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{userToken}}